Budenmayer542/Skeleton

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrders.cs
Testing4/TestingOrders.csproj
Testing4/tstOrders.cs

Everything is ok and there no errors.

Added testing for the orders class

---

Testing5/TestingProduct.csproj
Testing5/clsProduct.cs
Testing5/tstProduct.cs

Added test stuff

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrders.cs
Testing1/tstStaff.cs
Testing4/TestingOrders.csproj
Testing4/tstOrders.cs
Testing5/TestingProduct.csproj
Testing5/clsProduct.cs
Testing5/tstProduct.cs

added testing for the customer class

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsProduct.cs
Testing5/TestingProduct.csproj
Testing5/clsProduct.cs

Updated thingy, hopefully I do not bake

---

ClassLibrary/Assert.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/TestClass.cs
ClassLibrary/TestMethod.cs
ClassLibrary/clsCustomer.cs
Testing2/TestingCustomer.csproj
Testing2/tstCustomer.cs

added testing for Customer class

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsSupplier.cs
Testing3/TestingSupplier.csproj
Testing3/tstSupplier.cs

added testing for the supplier class

---

ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

Completed the test method and generated all properties. No errors.

Completed TestMethods

---

AdminSystem/OrdersDataEntry.aspx
AdminSystem/OrdersDataEntry.aspx.cs
AdminSystem/OrdersViewer.aspx
ClassLibrary/clsOrders.cs
Skeleton.sln
Testing4/tstOrders.cs

Progressed with creating the presentation layer for Orders table

---

ClassLibrary/clsProduct.cs
Testing5/tstProduct.cs

COMIC/PRODUCT update, testing

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsStaff.cs
Testing1/TestingStaff.csproj
Testing1/tstStaff.cs

practical 7 done

---

ClassLibrary/clsProduct.cs
Testing5/tstProduct.cs

Practical 7 completed :fire:

---

AdminSystem/OrdersDataEntry.aspx
AdminSystem/OrdersDataEntry.aspx.cs
AdminSystem/OrdersViewer.aspx
AdminSystem/OrdersViewer.aspx.cs
ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

Completed practical 8

---

AdminSystem/ProductDataEntry.aspx

Halfway Practical 8 I think

---

ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

Practical 9 almost completed

---

AdminSystem/ProductDataEntry.aspx

Minor improvements, still have to add :skull:

---

AdminSystem/OrdersDataEntry.aspx
AdminSystem/OrdersDataEntry.aspx.cs
AdminSystem/ProductDataEntry.aspx
AdminSystem/ProductDataEntry.aspx.cs
ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

All tests passed and no errors.

Completed practical 9b

---

AdminSystem/ProductDataEntry.aspx
ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

All tests pass so far and no errors

Progressing through practical 10

---

ClassLibrary/clsCustomer.cs
Testing2/tstCustomer1.cs

pratical 7 completed

---

ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

Mostly done with practical 10

---

ClassLibrary/clsOrders.cs
Testing4/tstOrders.cs

Finally completed practical 10

---

ClassLibrary/clsProduct.cs
Testing5/tstProduct.cs

Practical 10 progress (Also testing for conflicts :skul: )

---

AdminSystem/OrdersDataEntry.aspx.cs

All tests passed and no errors

Completed practical 11

---

ClassLibrary/clsProduct.cs
Testing5/tstProduct.cs

Practical 10 completed and fully working

Practical 10 done :D

---

AdminSystem/OrdersList.aspx
AdminSystem/OrdersList.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrdersCollection.cs
Testing4/TestingOrders.csproj
Testing4/tstOrdersCollection.cs

Completed practical 12

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerViewer.aspx.cs

done my practical 8

---

AdminSystem/ProductDataEntry.aspx.cs
AdminSystem/ProductList.aspx
AdminSystem/ProductList.aspx.cs
ClassLibrary/clsProduct.cs
ClassLibrary/clsProductCollection.cs
Testing5/tstProductCollection.cs

Practical 13a done :thumbsup:

---

AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerViewer.aspx.cs
ClassLibrary/clsCustomer.cs
Testing2/tstCustomer.cs

all tests pass. so completed my practical 9a

---

AdminSystem/OrdersDataEntry.aspx.cs
AdminSystem/OrdersList.aspx
AdminSystem/OrdersList.aspx.cs
ClassLibrary/clsOrdersCollection.cs
Testing4/tstOrdersCollection.cs

Completed 13b

---

AdminSystem/OrdersConfirmDelete.aspx
AdminSystem/OrdersConfirmDelete.aspx.cs
AdminSystem/OrdersDataEntry.aspx
AdminSystem/OrdersList.aspx
AdminSystem/OrdersList.aspx.cs
ClassLibrary/clsOrdersCollection.cs
Testing4/tstOrdersCollection.cs

Everything is working, no errors, and all tests pass.

Completed 14a

---

AdminSystem/OrdersList.aspx
AdminSystem/OrdersList.aspx.cs
ClassLibrary/clsOrdersCollection.cs
Testing4/tstOrdersCollection.cs

Everything functioning correctly, no errors, all tests pass.

Completed 14b

---

AdminSystem/OrdersLogin.aspx
AdminSystem/OrdersLogin.aspx.cs
AdminSystem/TeamMainMenu.aspx
AdminSystem/TeamMainMenu.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrdersUser.cs
Testing4/TestingOrders.csproj
Testing4/tstOrdersUser.cs

No errors, everything functional, all tests pass.

completed practical 15

---

AdminSystem/CustomerDataEntry.aspx
AdminSystem/CustomerDataEntry.aspx.cs

completed my practical 11

---

AdminSystem/CustomerDataEntry.aspx.cs
AdminSystem/CustomerList.aspx
AdminSystem/CustomerList.aspx.cs
ClassLibrary/clsCustomer.cs
ClassLibrary/clsCustomerCollection.cs
Testing2/tstCustomer.cs
Testing2/tstCustomerCollection.cs

completed practical 13 b

---

AdminSystem/CustomerList.aspx.cs
AdminSystem/CustomerLogin.aspx
AdminSystem/CustomerLogin.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomerUser.cs
Testing2/TestingCustomer.csproj
Testing2/tstCustomerCollection.cs
Testing2/tstCustomerUser.cs

dome practical 15
